spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springbootdb
    username: root
    password: hadoop
    driver-class-name: com.mysql.jdbc.Driver